-- Memory Brain System Migration
-- Creates tables for long-term semantic memory and session management

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create memories table for long-term semantic storage
CREATE TABLE IF NOT EXISTS memories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(768),  -- Gemini embedding dimension
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create user_sessions table for session tracking
CREATE TABLE IF NOT EXISTS user_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    session_buffer JSONB DEFAULT '[]'::jsonb,  -- Array of last 5-6 messages
    last_message_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id)
);

-- Create indexes for memories table
-- HNSW index for vector similarity search
CREATE INDEX IF NOT EXISTS memories_embedding_idx ON memories 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- Btree index on user_id for fast user lookups
CREATE INDEX IF NOT EXISTS memories_user_id_idx ON memories (user_id);

-- Index on metadata for filtering
CREATE INDEX IF NOT EXISTS memories_metadata_idx ON memories USING GIN (metadata);

-- Index on created_at for time-based queries
CREATE INDEX IF NOT EXISTS memories_created_at_idx ON memories (created_at DESC);

-- Indexes for user_sessions table
CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx ON user_sessions (user_id);
CREATE INDEX IF NOT EXISTS user_sessions_last_message_time_idx ON user_sessions (last_message_time);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers to auto-update updated_at
CREATE TRIGGER update_memories_updated_at BEFORE UPDATE ON memories
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_sessions_updated_at BEFORE UPDATE ON user_sessions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE memories IS 'Long-term semantic memories with vector embeddings for retrieval';
COMMENT ON TABLE user_sessions IS 'Short-term session buffers for active conversations';
COMMENT ON COLUMN memories.embedding IS 'Vector embedding generated by Gemini embedding model (768 dimensions)';
COMMENT ON COLUMN memories.metadata IS 'JSON metadata containing type, topic, tags, and other attributes';
COMMENT ON COLUMN user_sessions.session_buffer IS 'JSON array of last 5-6 messages in the current session';

